restylers:

  - clang-format:
      enabled: false

  - name: prettier
    arguments: ['--config=./.prettierrc', '--ignore-path=./.prettierignore']
    include:
      - '**/*.md'
      - '**/*.jsx'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.json'
