name: Lint
on: pull_request

concurrency:
  group: lint-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      - run: yarn
      - run: yarn run check-format
      - run: yarn run lint-ts
